### PR TITLE
Removing placeholders from Common Requirements pattern

### PR DESCRIPTION
**Pull request by spier**
This PR addresses some issues with the Common Requirements pattern that were raised in #386. 

### Key changes:

- Adding an anonymized Known Instance (as that is a content requirement for Structured patterns)
- Split Context into individual bullets
- Context: Replacing placeholders with short definitions and highlighting key terms
- Resulting Context: Replacing placeholder 
- Using enumeration to emphasize that that the solution consists of two aspects

### Ideas for future improvements:

There are some other quality issues with this pattern that are not addressed by this PR.
I left those out on purpose, to keep the review a bit lighter.

These things could be improved in future PRs:

- Improve the **Patlet** - escpecially describe how the solution is improving upon the problem
- Break up **Forces** into bullets - so that readers can check more easily if they have these forces as well
- Decide what to do with the **Resulting Context**: It currently focuses mostly on other related challenges that may need to be solved after this pattern is in place. However it lacks explanation of how this pattern has helped to address the problem.
- improving the [visual](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/main/assets/img/CommonReqtsv2.jpg) e.g. by creating a new version digitally (so no scan), and explaining in the patttern what that visual illustrates

### CODE REVIEW

**Comment by spier** [comment]
@jsmanrique would you mind reviewing this PR, to see if it helps with the issues you raised in #386 ?

**Review by NewMexicoKid — APPROVED** [review]
Proposed changes look okay to me. Do note that there are many different styles of writing patterns; back in the old days, expressing the context in paragraph form rather than in separate bullets was thought to be okay. That being said, I understand the value of breaking it down.

**Comment by spier** [comment]
Thanks for the review!

Absolutely, I also think paragraphs are ok in the Context. 
Personally I prefer one paragraph for each precondition in that case, as it makes it easier for the reader to use the Context as a checklist.

Even a mix might good in situations
e.g. some paragraphs in the beginning of the Context (kind of like a general intro) and then a bullet list of preconditions. 

I will see if I can get one more review and then merge this PR.

Thanks again!

**Comment by jsmanrique** [comment]
ILGTM. Thank you very much for reviewing this and working on the PR!

**Comment by spier** [comment]
Awesome. The improved pattern is now live at:
https://patterns.innersourcecommons.org/p/common-requirements

**Pull request merged**
