### PR TITLE
Added README for Hactoberfest

### PR DESCRIPTION
**Pull request by subashpaul**

### CODE REVIEW

**Comment by spier** [comment]
@subashpaul this README looks like a template from elsewhere. 
Can you point me to the original source it came from?

If this is just general information for hacktoberfest contributors I might opt to link to it, rather than to copy the full content into our repo.

**Comment by subashpaul** [comment]
its from [https://github.com/itsmedeepak/Hacktoberfest-2022]

**Comment by subashpaul** [comment]
[Here](https://github.com/itsmedeepak/Hacktoberfest-2022)

**Comment by spier** [comment]
Sorry @subashpaul but I cannot accept this PR, as I don't think it helps contributors with our repo here.

However if you want to review any of the files listed in https://github.com/InnerSourceCommons/InnerSourcePatterns/issues/464, feel free to send a new PR to improve those.

**Pull request closed without merging**
