### PR TITLE
Move patterns from wiki to markdown

### PR DESCRIPTION
**Pull request by spier**
Implements #132.

What I did:
* cloned [innersourcecommons.org/wiki](https://github.com/InnerSourceCommons/innersourcecommons.org/wiki)
* copied the respective markdown files into the [InnerSourcePatterns repo](https://github.com/InnerSourceCommons/InnerSourcePatterns) directly
* shortened the file names, while trying to keep the file names similar to the title of the original wiki pages.
* adapted the format of the patterns to the format in meta/pattern-template.md
* linked from each pattern to the original wiki page (we could remove this once the wiki pages get removed)

Suggestions for the reviewer:
- [x] compare the `.md` added here to the wiki pages I am linking below, to double check that I did not forget anything
- [x] some of the filenames are rather long. Maybe we can shorten them? Also I did not know if the files should be named after the **solution**, or rather after the **problem**?
- [x] delete the wiki pages, so that we don't have the same content in two places
- [ ] (possibly later in a new issue) there are some other pages in the wiki that look like patterns but they are not listed in this repo

Block by block, these are the patterns I ported.

## Block: "Pattern Drafts (proven, not yet fully reviewed)"

- [x] overcome-acquisition-based-silos-developer.md - [wiki/Overcome-Acquisition-based-Silos](https://github.com/InnerSourceCommons/innersourcecommons.org/wiki/Overcome-Acquisition-based-Silos)
- [x] overcome-acquisition-based-silos-manager.md - [wiki/Overcome-Acquisition-based-Silos](https://github.com/InnerSourceCommons/innersourcecommons.org/wiki/Overcome-Acquisition-based-Silos)

I decided to split this up into two separate pattern files. The original wiki page has some more info than these two markdown files but I did not know what to do with that.

So maybe keep this wiki page around? Not sure.

## Block: "Pattern Ideas (not yet proven; brainstormed)"

- [x] change-the-developers-mindset.md - [wiki/Pattern:-change-the-developers-mindset](https://github.com/InnerSourceCommons/innersourcecommons.org/wiki/Pattern:-change-the-developers-mindset)      
- [x] developer-incentive-alignment-for-innersource-contribution.md - [wiki/Donut:-Creating-Developer-Incentive-Alignment-for-InnerSource-Contribution](https://github.com/InnerSourceCommons/innersourcecommons.org/wiki/Donut:-Creating-Developer-Incentive-Alignment-for-InnerSource-Contribution) 
- [x] share-your-code-to-get-more-done.md - [wiki/Pattern:-Share-Your-Code-to-Get-More-Done---Likely-Contributors-Variant](https://github.com/InnerSourceCommons/innersourcecommons.org/wiki/Pattern:-Share-Your-Code-to-Get-More-Done---Likely-Contributors-Variant)    
- [x] shared-code-repo-different-from-build-repo.md  - [wiki/Shared-Code-Repo-Different-from-Build-Repo](https://github.com/InnerSourceCommons/innersourcecommons.org/wiki/Shared-Code-Repo-Different-from-Build-Repo)    

## Block: "Pattern Donuts (needing a solution)".

- [x] bad-weather-for-liftoff.md  - [wiki/Donut:-Bad-weather-for-liftoff
](https://github.com/InnerSourceCommons/innersourcecommons.org/wiki/Donut:-Bad-weather-for-liftoff)
- [x] defeat-hierarchical-constraints.md - [wiki/Donut-3%3A-how-to-defeat-the-hierarchical-constraints](https://github.com/InnerSourceCommons/innersourcecommons.org/wiki/Donut-3%3A-how-to-defeat-the-hierarchical-constraints)
- [x] organizational-mindset-change.md - [wiki/Donut-6:-organizational-mindset-change](https://github.com/InnerSourceCommons/innersourcecommons.org/wiki/Donut-6:-organizational-mindset-change)

### CODE REVIEW

**Comment by maxcapraro** [comment]
Thank you for this contribution, @spier 🎉 

I think it makes absolute sense to have all pattern content in one place (e.g. not some in the repo, some in a wiki). So imho this can be merged.

I'd like to ask for the advice of our experienced pattern yedi knights first: @NewMexicoKid, @gruetter @StingRayZA was there a reason for not having those patterns in the the repo yet?

**Review by lenucksi — APPROVED** [review]
I compared wiki and commit contents and it appears that it's properly moved. I say this LGTM and hence we should merge this.

Re: 
- yes, some filenames are longer. No one died from long filenames yet and we can still rename them later. (my 0,02€)
- delete wiki pages: yes, please after merging this.
- follow up on possible pattern content: sounds good. Could you please transform that into an issue with what you've found such that we can handle this later @spier?

**Comment by spier** [comment]
Follow-up stories:

* delete wiki pages that were ported https://github.com/InnerSourceCommons/innersourcecommons.org/issues/134
* after that, port also the remaining wiki pages https://github.com/InnerSourceCommons/InnerSourcePatterns/issues/143

**Comment by rrrutledge** [comment]
Nice work!

**Pull request merged**
