### PR TITLE
Standardize title section

### PR DESCRIPTION
**Pull request by spier**
While working on the automation for the book creation, I needed to parse out the pattern titles from the markdown files. 
I realized that some titles are using a different formatting, which makes the parsing harder and the book also looks a tiny bit inconsistent then.

In this PR I change this:
- remove italics from titles
- move aliases for pattern titles to a separate `Alias` section. This gives the pattern one clear **main name**. the aliases could later be used as separate links to the same pattern if we like to do that.

@lenucksi we don't have the "Alias" section header defined in the Pattern template. However I assumed that extra headers are fine to add, as long as they don't contract the other headers. 

Should I add a definition of the "Alias" section to the Pattern template file as well?

### CODE REVIEW

**Comment by lenucksi** [comment]
> While working on the automation for the book creation, I needed to parse out the pattern titles from the markdown files.
> I realized that some titles are using a different formatting, which makes the parsing harder and the book also looks a tiny bit inconsistent then.
> 
> In this PR I change this:
> 
> * remove italics from titles
>
> * move aliases for pattern titles to a separate section (this gives the pattern one clear **main name**. the aliases could later be used as separate links to the same pattern if we like to do that)

Thanks, looks good to me.
> 
> 
> @lenucksi we don't have the "Alias" section header defined in the Pattern template. However I assumed that extra headers are fine to add, as long as they don't contract the other headers.
> 
> Should I add a definition of the "Alias" section to the Pattern template file as well?

If we assume this to be used consistently it should go into what currently is used for sort-of "documentary" purposes, i.e. the template. 
Also having this in a separate section will allow us to use this to index or other parser uses later on.

**Review by lenucksi — CHANGES_REQUESTED** [review]
Should document the use of alias in the pattern template as illustrated above. Good otherwise.

**Comment by spier** [comment]
Done!

**Review by lenucksi — APPROVED** [review]
LGTM

**Pull request merged**
