### PR TITLE
[TEST] Update JA gitbook with latest from `main`

### PR DESCRIPTION
**Pull request by spier**
Goal: Publish the latest changes to the Japanese translation.

_Note:_ Currently we are doing this manually. Eventually we want to automate it. Expect some bumps in the road :)

### CODE REVIEW

**Comment by spier** [comment]
Hmm. I don't know why we are ending up with conflicting files here.

Possibly because I did "rebase and merge" to update the branch the last time in #445 ?

**Comment by spier** [comment]
The `book-ja` branch is a long-lived branched (previously the name was `book-jp` but it is the same branch).

Both in this PR here, as well as in #445 I merged `main` into `book-ja`.

I had expected that this PR would not have any conflicts and just be "ready to merge" as is.
However this PR surprized me in two ways:

1. I see commits that were already merged previously. See picture below.
2. There are conflicts that need to be resolved before merging.

I don't know why that happens.

I should mention that we have a GitHub Action that runs on the `book-ja` branch, which will create a new commit that does not exist on `main`. Possibly that is contributing to the issue?

Duplicate commits, i.e. commits that should already exist on the `book-ja` branch, are:

Screenshot 2022-09-18 at 09 14 43

**Review by yuhattor — APPROVED** [review]
lgtm

**Review by yuhattor — APPROVED** [review]

**Review by yuhattor — APPROVED** [review]
lg:)

**Comment by spier** [comment]
Yeah this PR is problematic. It  contains all the latest additions to 'main'. However there are some conflicts that need to be resolved first. Confusing. Not sure why this got into this state.

**Comment by spier** [comment]
This PR is getting updated with any new commits to `main`, as this PR is merging `main` into `book-ja`.
However we have a bunch of conflicts in the merge, that I don't really understand.

**Comment by robtuley** [comment]
If it helps I think the conflict isn't actually as bad as GitHub UI is suggesting...

```
InnerSourcePatterns git:(book-ja) git merge main 
... <snip> ...
CONFLICT (content): Merge conflict in book/README.md
CONFLICT (content): Merge conflict in README.md
CONFLICT (content): Merge conflict in CONTRIBUTING.md
CONFLICT (add/add): Merge conflict in .lycheeignore
CONFLICT (content): Merge conflict in .github/workflows/link-checker.yml
Automatic merge failed; fix conflicts and then commit the result.

InnerSourcePatterns git:(book-ja) git status 
<snip>

Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)
        both modified:   .github/workflows/link-checker.yml
        both added:      .lycheeignore
        both modified:   CONTRIBUTING.md
        both modified:   README.md
        both modified:   book/README.md
        deleted by them: book/jp/toc.md
        both modified:   translation/README.md
```

**Comment by robtuley** [comment]
> Possibly because I did "rebase and merge" to update the branch the last time in #445

Yeah maybe -- I think using a merge commit is needed and will make it simpler in terms of history. I created a new branch `book-ja-with-main-merged` from current `book-ja`, then merged in main, did my best to resolve the conflicts (I prevented the delete of `book/jp/toc.md` not sure about that?), and then stuck it in #493 -- is that perhaps easier to work forward with?

**Comment by robtuley** [comment]
Crap, I'm now wondering whether `book-ja-with-main-merged` was a terrible temporary branch name choice given it matches `book-*`, erm.. hopefully that doesn't do anything I didn't intend.

**Review by yuhattor — APPROVED** [review]

**Comment by spier** [comment]
Deleting old branch, as the book release for other languages doesn't work well like this anyways.
Will be using a new approach soon, using gitbooks new "monorepos" configuration (see #578).

**Pull request closed without merging**
