### PR TITLE
Document the approach used for the pattern categorization

### PR DESCRIPTION
**Pull request by spier**
Hi @fwan2000,

I took your great visualization of the patterns, and added some further explanations to it.

## What is the motivation for this?

* allow readers to understand what this mind map is => by pulling relevant information from conversations in slack and from #150 into `./pattern-categorization.README.md`
* enable contributors to edit and regenerate the mind map
* separate the visualization from the patterns itself => by moving it into a subfolder `./pattern-categorization`

Hope this is helpful.

Cheers
/Sebastian

### CODE REVIEW

**Review by fwan2000 — APPROVED** [review]
@spier Thanks for the README.md! It provides good background and clarity on how the categorization works. Moving those to its own directory is also a great idea. Thanks!

**Comment by spier** [comment]
@fwan2000 awesome, thanks for the quick reply.

**Comment by spier** [comment]
Hi @lenucksi. I think from the Trusted Committers you know most about the files that are changed in here. I already got the ok from the original author (see above). So I just need somebody to merge this :)

**Review by lenucksi — APPROVED** [review]
Nice! :tada:

**Pull request merged**
