### PR TITLE
Update gig-marketplace.md

### PR DESCRIPTION
**Pull request by shreyansdugar**
Stephen and I worked on this jointly while working for the financial services org

### CODE REVIEW

**Comment by spier** [comment]
Great to know, thanks for the addition @shreyansdugar. 

Do you want to add anything else to the content of the pattern as well?

**Comment by shreyansdugar** [comment]
Rest of the pattern looks good, thanks for checking :)

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by spier** [comment]
@lenucksi I have asked Stephen in Slack if he can confirm this. Do you think that is a good approach? I am not sure how else we could be able to validate this?

**Comment by lenucksi** [comment]
> 
> 
> @lenucksi I have asked Stephen in Slack if he can confirm this. Do you think that is a good approach? I am not sure how else we could be able to validate this?

It's a valid approach. I could already confirm that @shreyansdugar worked at Fidelity at the time and they know each other.
@stephenmccall will come back to us. Maybe even with some help to get the outstanding Fidelity-sponsored PRs further.

**Review by spier — APPROVED** [review]
Stephen confirmed. This is good to be merged.

**Pull request merged**
