### PR TITLE
Adding GovTech GPSL as a Known Instance to the InnerSource License pattern

### LINKED ISSUE #604: Add Known Instance to InnerSource Licenses: Singapore Government
See https://youtu.be/-zu2X2iERv8?feature=shared&t=1257 (around 20:50)

### PR DESCRIPTION
**Pull request by spier**
Closes #604.

Adding GovTech (Singapore Government) as a known instance to the InnerSource License pattern.
Description based on this [ISC community call](https://www.youtube.com/watch?v=-zu2X2iERv8&t=1257s&ab_channel=InnerSourceCommons).

### CODE REVIEW

**Comment by spier** [comment]
@hunter once merged, this PR would add the GovTech GPSL as a known instance to this pattern here:
https://patterns.innersourcecommons.org/p/innersource-license

Such known instances of organizations that have implemented a given InnerSource patterns help us to showcase the validity of a given pattern, and harden and improve the content of the pattern overall.

It would be really awesome to get your review of the text here, which I extracted from the ISC community call that you presented at recently.

Some questions that I have:
- correct spelling of GovTech?
- which license did you base the GPSL on?
- is the GPSL license text publicly available somewhere, so that others could use it as inspiration?

Thank you so much for your help!

And also thanks again to @dellagustin-sap for spotting this in the community call :)

**Comment by dellagustin-sap** [comment]
Creating an issue as a note to yourself to work on it later and having someone else picking it up is one of the beauties of Open Source!
Thanks a lot @spier for the PR. I did a quick check my self and it is looking good.

**Review by hunter — APPROVED** [review]
LGTM

**Comment by spier** [comment]
This is now live at https://patterns.innersourcecommons.org/p/innersource-license

Thanks @dellagustin-sap for the pointer and @hunter for description and confirmation!!!

**Comment by dellagustin-sap** [comment]
@spier @hunter teamwork makes the dream work 👍 😄

**Pull request merged**
