### PR TITLE
Publishing patterns book in Chinese (zh)

### PR DESCRIPTION
**Pull request by spier**
Combining the existing work done in #513 and #514.

### CODE REVIEW

**Comment by spier** [comment]
@WillemJiang this branch is now live at 
https://innersourcecommons.gitbook.io/innersource-patterns-staging/v/zh-test/

This is the Staging system of our patterns book, which we just use for testing.

If you could take a look and check if things look as expected that would be great.

The main changes I have done:
- rename folders from `cn` to `zh` (to use the 2-letter language code)
- changed the section heading of the patterns back to "Title". Otherwise our automation was not able to generate the table of contents needed for gitbook. See [d88e7dd](https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/515/commits/d88e7dd6c68d329a58ef777ca8eda929aa01b6f9)

Other notes:

- [x] we should reduce the size of the book cover (seems to be larger than the ones we used for the other books)
- [ ] determine which font to use for Chinese in gitbook
- [x] the error that the link checker reports will probably resolve itself in the next run
- ... tbd

**Comment by spier** [comment]
@WillemJiang all your latest changes are now integrated here. You can review them at:
https://innersourcecommons.gitbook.io/innersource-patterns-staging/v/zh-test/

High-level this now all looks good to me but of course I don't speak Chinese so I cannot really review this :)

Once you confirm this is all correct now, then I can merge this branch and get it published in our Production gitbook, so that the world can enjoy the InnerSource patterns in Chinese 🇨🇳 👍

**Comment by WillemJiang** [comment]
> https://innersourcecommons.gitbook.io/innersource-patterns-staging/v/zh-test/

@spier, thanks for your efforts in putting all the translation files together.  I will go through the Chinese book to see if any obvious errors need to be fixed.

**Comment by WillemJiang** [comment]
@spier I just sent a PR https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/516 for it.

**Comment by spier** [comment]
@WillemJiang looks good. All merged now.

Once you reviewed everything, could you leave an approval review on this PR?

**Comment by WillemJiang** [comment]
@spier I created another PR https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/517 to fix some minor typos I found recently.

**Comment by spier** [comment]
@WillemJiang thank you! All merged.

Two questions:

1. I noticed that you kept "Trusted Committer" in English, maybe because it is a specific InnerSource term that would be difficult to translate?
2. Wonder how you and @hncslwx did the review process, as it looks like you did this outside of GitHub? Just curious about this to see if there is something that we can learn from this for future translations in other languages.

**Comment by WillemJiang** [comment]
> @WillemJiang thank you! All merged.
> 
> Two questions:
> 
> 1. I noticed that you kept "Trusted Committer" in English, maybe because it is a specific InnerSource term that would be difficult to translate?

Yes, it's hard to find the right word in Chinese for the "Trusted Committer", so we keep using the English term. 

> 2. Wonder how you and @hncslwx did the review process, as it looks like you did this outside of GitHub? Just curious about this to see if there is something that we can learn from this for future translations in other languages.

You can find more information about the review information [here](https://github.com/WillemJiang/InnerSourcePatterns/pulls?q=is%3Apr+is%3Aclosed). 

BTW, Big +1 for us to build a common translation process.

**Comment by spier** [comment]
Got it. So the reviews happen as conversations on the PRs of your fork. 

Do you have a list of contributors that we should attribute this translation work to? Then we could mention them once we merge this branch, so that they get properly acknowledged in the contributor chart on our main repo.

**Comment by WillemJiang** [comment]
> Got it. So the reviews happen as conversations on the PRs of your fork.
> 
> Do you have a list of contributors that we should attribute this translation work to? Then we could mention them once we merge this branch, so that they get properly acknowledged in the contributor chart on our main repo.

Yeah, it's a great idea, I can add a comment with all the contributors in this PR.

**Comment by WillemJiang** [comment]
> Got it. So the reviews happen as conversations on the PRs of your fork.
> 
> Do you have a list of contributors that we should attribute this translation work to? Then we could mention them once we merge this branch, so that they get properly acknowledged in the contributor chart on our main repo.

Yeah, it's a great idea, I can add a comment with all the contributors in this PR.

**Comment by spier** [comment]
Great.

I think we can use this syntax, for which we only need the GitHub user name.

> Co-authored-by: WillemJiang <WillemJiang@users.noreply.github.com>

This is just a guess though, as I did not find this exact syntax explained in the [GitHub docs](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors).

**Comment by WillemJiang** [comment]
> Great.
> 
> I think we can use this syntax, for which we only need the GitHub user name.
> 
> > Co-authored-by: WillemJiang [WillemJiang@users.noreply.github.com](mailto:WillemJiang@users.noreply.github.com)
> 
> This is just a guess though, as I did not find this exact syntax explained in the [GitHub docs](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors).

It was added by github action which just generates the TOC, can we just ignore it?

**Comment by WillemJiang** [comment]
Thanks for the contributions from 
```
[姜宁 Willem Jiang]:(https://github.com/willemjiang)
[龙文选 Wenxuan Long]:(https://github.com/hncslwx)
[孙振华 Zhenhua Sun](https://github.com/sunzhh02)
[陈泳 Yong Chen](https://github.com/gzchenyong)
[谭中意 Jerry Tan](https://github.com/tanzhongyi003)
[安旭 Xu An](https://github.com/anzipomelo)

```

**Comment by spier** [comment]
Excellent. Committing this as:

```
Co-authored-by: Willem Jiang <WillemJiang@users.noreply.github.com>
Co-authored-by: Wenxuan Long <hncslwx@users.noreply.github.com>
Co-authored-by: Zhenhua Sun <sunzhh02@users.noreply.github.com>
Co-authored-by: Yong Chen <gzchenyong@users.noreply.github.com>
Co-authored-by: Jerry Tan <tanzhongyi003@users.noreply.github.com>
Co-authored-by: Xu An <anzipomelo@users.noreply.github.com>
```

Finger's crossed that it works and you all get your credits in the contribution graph! :)

**Comment by spier** [comment]
@WillemJiang looks like the attribution worked as expected:

Screenshot 2023-01-04 at 20 49 10

**Comment by spier** [comment]
@WillemJiang @hncslwx @sunzhh02 @gzchenyong @tanzhongyi003 @anzipomelo your Chinese translation of the InnerSource patterns are now live at: [patterns.innersourcecommons.org/v/zh/](https://patterns.innersourcecommons.org/v/zh/)

Would be great to advertise this broadly in the Chinese-speaking InnerSource community :)

Fantastic work. You should be really proud of what you achieved here!
I will also send some shout outs to all of you in Slack.

**Pull request merged**
