### PR TITLE
Patterns WG report for 2020-11 board meeting

### PR DESCRIPTION
**Pull request by spier**
Patterns WG report for 2020-11 Board meeting.
Reporting Period: **2020-10**

### CODE REVIEW

**Review by NewMexicoKid — APPROVED** [review]
Looks good. Thanks for your continued good work. I think that some targeted topic office hour sessions advertised in advance might help generate more interest in the community.
Wish I had more time in my day job to help out; hoping to get some time in 2021.

**Comment by spier** [comment]
> Wish I had more time in my day job to help out; hoping to get some time in 2021.

Fingers crossed for 2021 then. Looking forward to it! :)

**Comment by lenucksi** [comment]
> Looks good. Thanks for your continued good work. I think that some targeted topic office hour sessions advertised in advance might help generate more interest in the community.
> Wish I had more time in my day job to help out; hoping to get some time in 2021.

That and surely executing (even in an automated manner) the crier function making more people aware of the existence of the office hours might be useful.

**Review by lenucksi — APPROVED** [review]
This looks good, thanks for creating it @spier.

**Pull request merged**
