### PR TITLE
chore: change either to any

### PR DESCRIPTION
**Pull request by jmeridth**
In its current context, there are 3 choices so `any` is more appropriate.  `either` is for binary decisions (between 2 choices).

### CODE REVIEW

**Review by spier — APPROVED** [review]
Thank you for the fix. Hope you found it easy enough to figure out how to contribute?

Many of our patterns were written by contributors that speak English as a foreign language. So I am sure there are many more language/grammar improvements like this to be made 😃 

Thanks again!

**Comment by jmeridth** [comment]
@spier Yes.  Contribution process was very easy. Thank you.  I'm re-reading the entire patterns book again and may have other PRs.  This one was the gateway PR and felt very nitpicky but thank you for merging it.  Cheers.

**Comment by spier** [comment]
That's great @jmeridth. Looking forward to any and all contributions that you want to make. 

And no worry about nitpicking, if we really don't want to make a change that you are suggesting, we can just talk about that in any future PRs. No harm done, quite the opposite actually, as it is always great to have somebody with fresh eyes read our patterns again!

**Comment by spier** [comment]
Btw your change is not live in https://patterns.innersourcecommons.org/p/common-requirements yet. Not sure how much delay we should expect there. Will confirm with the gitbook service (which is where we are hosting our book).

**Pull request merged**
