### PR TITLE
Updated pattern maturity of patterns in markdown format

### LINKED ISSUE #128: Pattern Maturity in patterns does not match defined pattern-states nomenclature
I am making this assumption:

The `#Status` defined in [pattern-template.md](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/meta/pattern-template.md) is meant to be one of the defined [pattern-states](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/meta/pattern-states.md).

Assuming that the above is true:

When reading some of the existing patterns I found that some of them don't have a `#Status` set at all, while others have one but they don't match the defined [pattern-states](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/meta/pattern-states.md).

Would it be worth fixing this, so that all patterns specify what their Pattern Maturity is, following the [pattern-states](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/meta/pattern-states.md).

For reference some examples of patterns and their `#Status`:

```
$ egrep -A2 "Status|State\s*$" InnerSourcePatterns/*.md

InnerSourcePatterns/30-day-warranty.md:# State
InnerSourcePatterns/30-day-warranty.md-Drafted at the 2017 Spring InnerSource Summit; reviewed 18 July 2017.
--
InnerSourcePatterns/common-requirements.md:## Status
InnerSourcePatterns/common-requirements.md-Shepherded pattern
--
InnerSourcePatterns/contracted-contributor.md:## Status
InnerSourcePatterns/contracted-contributor.md-_Proven Pattern_
--
InnerSourcePatterns/dedicated-community-leader.md:## Status
InnerSourcePatterns/dedicated-community-leader.md-_Reviewed Pattern_
--
InnerSourcePatterns/discover-your-innersource.md:## Status
InnerSourcePatterns/discover-your-innersource.md-Brainstormed pattern idea in progress
--
InnerSourcePatterns/improve-findability.md:## Status
InnerSourcePatterns/improve-findability.md-Brainstormed pattern idea reviewed 2017-03-11.
--
InnerSourcePatterns/introducing-metrics-in-innersource.md:# State
InnerSourcePatterns/introducing-metrics-in-innersource.md-Early Idea
--
InnerSourcePatterns/junkyard-styled-innersourcing.md:## Status
InnerSourcePatterns/junkyard-styled-innersourcing.md-Brainstormed pattern idea in progress
--
InnerSourcePatterns/modular-code.md:**Status:**
InnerSourcePatterns/modular-code.md-Donut
--
InnerSourcePatterns/review-committee.md:## Status
InnerSourcePatterns/review-committee.md-_Finalized and Reviewed_ as of 8/31/17.
--
InnerSourcePatterns/start-as-experiment.md:# Status
InnerSourcePatterns/start-as-experiment.md-Proven Pattern
```

### PR DESCRIPTION
**Pull request by spier**
Fixes #128.

- added/updated the "## Status" section for the patterns listed in README that are available as `.md` files
- also ordered the sections according to the order in `pattern-template.md`.
- fixed some minor typos too

## Warning

Looks like my editor removed a bunch of spaces at the end of lines automatically?
I don't really know how that happened.

Unfortunately that makes the diff below a bit harder to read.

## Other Observations

* Prerequisites
  * found in: gig-marketplace.md, innersource-portal.md
  * not part of the Pattern template
* "Solution"/"Solutions" / is used in singular and plural form in the patterns
* "Author","Authors","Author(s)"
* do we want newline after headlines in the `.md` files? Tiny difference admittedly :)
* "Patlet" section was missing from some patterns. I added a placeholder for it. e.g. review-committee.md
* sections that appear in some patterns but are not part of the Pattern template
  * `See also`
  * `Related Patterns`
  * `Variants`
  * `Also Known As`
* having only one pattern in the folder "project-roles", while all other `.md` files are in the root folder is confusing

### CODE REVIEW

**Comment by spier** [comment]
@rrrutledge I am not done yet but I submitted this as a draft PR, so that you can see in which direction I am going with this.

Would you mind taking a look, so that I am not overdoing it?

**Review by rrrutledge — APPROVED** [review]
Great!

**Comment by rrrutledge** [comment]
Everything that is there looks good.

**Comment by spier** [comment]
@rrrutledge I think that this is a good enough iteration i.e. I am happy with this to be merged, if you think the changes make sense.

**Pull request merged**
