### PR TITLE
Moving Japanese content to `translation/jp`

### PR DESCRIPTION
**Pull request by spier**
This PR contributes to a part of #430.

I moved all files from `translation/japanese` to `translation/jp` and adapted scripts and docs that contained the old folder name.

By changing this folder name things are more consistent with branch names (`book-jp`) the other book files (`/book/jp`) etc.

Deployed a staging version of this to:
https://innersourcecommons.gitbook.io/innersource-patterns-staging/v/jp-new-folder/

As part of this I also improved the GHA workflow.
Now any folder starting with `book-jp` will generate the Japanese book, which should be helpful for testing purposes.

### CODE REVIEW

**Comment by spier** [comment]
@yuhattor could you review this?

In theory it is a relatively small change but as I am moving/touching all files, I want to make sure that I did not break anything.

**Review by yuhattor — COMMENTED** [review]
@spier 
Very nice!
Just a little input from the community, but jp represents the country and ja represents the locale. If we ever get a Chinese translation in the future, it might be a good idea to adapt the i18n rules sometime in the future. For now, I think jp is fine.
But I don't want to change it too often from SEO point of view. I thought maybe this could be fixed now. What do you think?

**Comment by spier** [comment]
Oh, good one.

So do you want to replace `jp` with `ja` everywhere?

- branch name => `book-ja`
- book URL => `https://patterns.innersourcecommons.org/v/ja/`
- folder name => `translation/ja`
- ... (maybe we got some wherewhere else too?)

If we want to change it, then we should do it very soon though (SEO / not breaking links).
I would suggest to do this in a new PR though (I can take care of that, if you like).

**Comment by yuhattor** [comment]
I think so. I'll ask the community for some input. We are generally more familiar with jp than ja.
As you said, I think it would be good to do it somewhere different from this PR for once:)

If you think it's good as it is now, please merge it:)

**Comment by spier** [comment]
> [...] We are generally more familiar with jp than ja. [...]

@yuhattor Did you get this the wrong way around possibly?

Earlier I understood that `ja` is the correct language short code to use, right?

> If you think it's good as it is now, please merge it:)

I actually changed my mind on this.

Let's wait until you got input from the Japanese community. Then I can adapt this PR as desired, merge it, and change the gitbook config to build from the correct branch and use the desired URL prefix.

That way we only do this work once, and not twice :)

**Comment by yuhattor** [comment]
Sorry, that was confusing.

Now let's change patterns to ja!
ja is the official i18n term.
This is also how it looks on innersourcecommons.org
https://innersourcecommons.org/ja/learn/learning-path/

The Japanese community is basically trying to comply with Upstream. And ja is the "correct" code.
So we decided to go with ja. Thank you always, I'd appreciate it if you could fix it!

**Comment by spier** [comment]
I renamed the branch from `book-jp-folder-move` to `book-ja-folder-move` in order to get the modified GHA to run.
That automatically closed this PR as well. Did not know that that would happen but makes sense I guess :)

**Comment by spier** [comment]
Continued this work in https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/452

**Pull request closed without merging**
