### PR TITLE
Fixing some typos in the MaturityModel pattern

### PR DESCRIPTION
**Pull request by spier**
There is at least one other typo in there ("oportunity").
Want to see if the bot catches that :)

### CODE REVIEW

**Comment by spier** [comment]
@lenucksi how can I be sure that prosebot actually checked the .md files in this PR?

**Comment by lenucksi** [comment]
> @lenucksi how can I be sure that prosebot actually checked the .md files in this PR?

From what's in the documentation it should have been visible as a pull request check here and added custom notes. 
Apparently that did not work out as expected, which means that there's the test I wanted in #218. Looks like that one needs fixing.

 Also, Linkbot was unhappy about this link: https://github.com/open-organization/open-org-distributed-work-guide/blob/master/drostfromm_remote-first-through-openess.md#setting-cross-team-standards-and-best-practices-in-the-open

The file is still present and hence but changes so either we reference the [file without anchor](https://github.com/open-organization/open-org-distributed-work-guide/blob/master/drostfromm-remote-first-through-openess.md) or just update the link

**Comment by spier** [comment]
I have already fixed the broken link as part of https://github.com/InnerSourceCommons/InnerSourcePatterns/pull/225, which has been merged to master in the meantime.

Do you want to keep this PR here open as a test for your prosebot? Otherwise I can rebase this on master and we can get it merged.

**Comment by lenucksi** [comment]
Lets merge this for now and keep an intentionally defect PR around to test linters. Found some other bots / linter integrations in case prosebot doesn't go where want it to.

**Pull request merged**
