### PR TITLE
Add new translation language: Galician

### PR DESCRIPTION
**Pull request by psanxiao**
This PR adds a new entirely translation to Galician language. Includes:

- Translation of the structured patterns in translation/gl folder
- Translation of the files within folder 'book'  in book/gl folder
- Translation of some of the graphics, that we created in a new gl folder into assets/img/gl

This translation was made possible thank you to [Xunta de Galicia](https://amtega.xunta.gal), local goverment of Galicia region, as part as project to foster InnerSource practiques among the Galician companies.

People who participate in the translation work were:
- Leticia Gómez Cadahía
- María Lucía González Castro

We hope you find interesting this contribution and we looking forward to your feedback. Let us know any change that we should made so that this PR could be integrated.

Thank you in advance for your time.

### CODE REVIEW

**Comment by spier** [comment]
Awesomeness in the making @psanxiao! Will get back to this shortly.

**Comment by spier** [comment]
@psanxiao thank you again for this contribution.

I made various tiny fixes to the markdown formatting. Those were just house-keeping items though, that make it simpler for us to maintain these patterns.

Further I found some broken links, which I fixed as well.

Just for two of these links I wasn't sure. I found these links to files that don't exist:
- `meta/gl/pattern-template.md`
- `innersource-program-mind-map.png`

I have fixed those links as well to point to the English version of those files instead. If you were still intending to translate those files to Galician too, you can certainly do that. However you don't have to as the translations to Japanese/Chinese etc have not done that either (i.e. they kept the English versions as well).

Also at least for the mind-map it will be a bit trickier to do the translation, as we have some automation there that generates the mindmap, which we would have to fix too.

**Comment by psanxiao** [comment]
Thank you very much @spier for reviewing and for all the fixes.

About those links that you mentioned, yeah, it was my fault. I did not upload those files in the previous commits. But, taking into account what you say, maybe it has no sense to upload the translation for those files.

**Comment by spier** [comment]
Oh, well if you already have those fixes anyways, by all means, please add them to the PR @psanxiao !

**Comment by spier** [comment]
Btw there is something that I need to clarify with the gitbook Support team before publishing the Galician version of the patterns. So it will likely take until early next week. Just to set expectations :)

**Comment by psanxiao** [comment]
> Btw there is something that I need to clarify with the gitbook Support team before publishing the Galician version of the patterns. So it will likely take until early next week. Just to set expectations :)

No problem with that. Thank you very much for all your work done.

**Comment by spier** [comment]
> > Btw there is something that I need to clarify with the gitbook Support team before publishing the Galician version of the patterns. So it will likely take until early next week. Just to set expectations :)
> 
> No problem with that. Thank you very much for all your work done.

You got it :)

Actually I think I was able to resolve the issue.
Should be able to release a bit sooner then :)

**Comment by spier** [comment]
Note to self:
We will have to re-work the `generate-mindmap.yml` GitHub Action, to make sure that we re-generate the mindmap for Galician as well, if the input files change.

**Comment by spier** [comment]
Also after this PR we get to do some continuity testing immediate, as in the meantime there is another pattern that needs translation :) (see [Standard Release Process](https://patterns.innersourcecommons.org/p/release-process))

**Review by spier — APPROVED** [review]

**Comment by spier** [comment]
I think I checked this PR sufficiently now, and am happy to get this merged tomorrow, and published in our online book. This will be so cool 🥳 

One more question for you though @psanxiao: 
For each translation we have a translation lead. We have established that concept, as we don't speak these languages ourselves, so naturally we cannot review future contributions to these translations ourselves.

So, would you like to be the translation lead for Galician? :)

**Comment by psanxiao** [comment]
> 
> So, would you like to be the translation lead for Galician? :)

Sure! :)

**Comment by spier** [comment]
I think I already said it more than once, but it doesn't hurt:
Thank you again for all your work @psanxiao !!! ❤️ 

This is now [live](https://github.com/InnerSourceCommons/InnerSourcePatterns/releases/tag/v1.9) :)

**Pull request merged**
