### PR TITLE
initial submission for categorization md and mindmap image

### PR DESCRIPTION
**Pull request by fwan2000**
This is a categorization effort to use mind map to categorize proven patterns & some other lower maturity level patterns based on InnerSource program stage and challenges at the stage. Discussions are in issue #15 .

We use markdown file for mind map creation. Markdown file allows easy collaboration to make changes. svg file is created for the mind map visualization. It uses an Atom plugin: https://atom.io/packages/markdown-mindmap

The markdown file can also be used with an open source javascript library to visualize it on website:  https://github.com/dundalek/markmap

Here's how the svg picture looks like: 
image

### CODE REVIEW

**Review by lenucksi — APPROVED** [review]
Thanks! This is great stuff. 
I wonder if there is a library that is capable of rendering SVGs from the markdown using the command-line? (To auto-update & auto-generate the SVG upon commits using GitHub actions such that it can be used in PDFs and ePUBs)
The Atom library looks like and extension for the editor that will actually need a GUI and the editor. Or did I misinterpret that?

**Comment by lenucksi** [comment]
I found the tools that do diagram rendering from text that that I was looking for the other time: 
- https://github.com/gera2ld/markmap-lib This looks especially relevant as it supposedly builds upon the atom extension but enables CLI use you. @fwan2000 would you mind giving this a spin if it actually is capable of rendering your nice diagram to SVG on the command line?
- https://mermaid-js.github.io/mermaid/#/

Notable mention:
- https://asciidoctor.org/docs/asciidoctor-diagram/
- https://ivanceras.github.io/svgbob-editor/

**Comment by fwan2000** [comment]
> I found the tools that do diagram rendering from text that that I was looking for the other time:
> 
> * https://github.com/gera2ld/markmap-lib This looks especially relevant as it supposedly builds upon the atom extension but enables CLI use you. @fwan2000 would you mind giving this a spin if it actually is capable of rendering your nice diagram to SVG on the command line?
> * https://mermaid-js.github.io/mermaid/#/
> 
> Notable mention:
> 
> * https://asciidoctor.org/docs/asciidoctor-diagram/
> * https://ivanceras.github.io/svgbob-editor/

@lenucksi Thanks a lot for find the markmap-lib! It can create a nice HTML with svg as part of it. I will update PR with the HTML created from the markmap-lib.

**Comment by fwan2000** [comment]
@lenucksi Update md files with links to the patterns and create html for the mind map. The HTML can be used in website for mind map style pattern navigation.

**Comment by fwan2000** [comment]
Here's the instruction on creating the html:
```
npm install markmap-lib -g
markmap IS.md
```

**Comment by fwan2000** [comment]
We can also use Github Page to host HTML files and link to the IS.html for users to navigate to the patterns by challenges.

**Comment by lenucksi** [comment]
@fwan2000 This sounds even better if it allows us to create something clickable additionally to something that is useful in "print" ;) 
I'll try this out later this week and report back then!

**Review by lenucksi — APPROVED** [review]
Tried this and it looks nice and works in my browser. SVG seems to be extractable for print.

**Comment by fwan2000** [comment]
@lenucksi Any other changes needed for this to be merged?

**Comment by lenucksi** [comment]
> @lenucksi Any other changes needed for this to be merged?

I don't think so. Just a bit of time on my side, which currently is a bit sparse. Will probably get around to merging mid of the week.

**Comment by lenucksi** [comment]
> > @lenucksi Any other changes needed for this to be merged?
> 
> I don't think so. Just a bit of time on my side, which currently is a bit sparse. Will probably get around to merging mid of the week.

This is still great stuff, we just need to remember to add a GitHub Action to regenerate the SVG / HTML / rendered products once the .md changes and make a checklist item for PRs to update the .md once new things come in to keep everything fresh. 
And thanks for creating all of this @fwan2000! :D

**Pull request merged**
