### PR TITLE
Shortening some pattern titles to make for nicer links

### PR DESCRIPTION
**Pull request by spier**
Shortening some pattern titles to make for nicer links. Preparing for our book release (see #173).
I moved the long form of the titles to the Alias section where that seemed useful.

### CODE REVIEW

**Comment by spier** [comment]
@MaineC I touched a couple of the patterns that you contributed in here. Are you happy with the changes that I made to the pattern titles?

**Comment by spier** [comment]
@dicortazar I touched a pattern hat you contributed in here. Are you happy with the changes that I made to the pattern titles?

**Comment by gruetter** [comment]
I like all of the new, more concise titles. Wondering if we need the _Alias_ section at all, @spier . I feel that the extra text in this section should not be necessary if there's a good patlet. Also, I would expect equally short, alternative titles in the _Alias_ section rather than "elaborations" on the existing title. Just my 0.02 $. @NewMexicoKid , WDYT?

**Comment by spier** [comment]
Yeah, I understand your line of thinking about the Aliases.

The **Alias** section is something that we introduced a couple of months ago, and the only pattern where I recall using it so far is [Dedicated Community Manager](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/patterns/2-structured/dedicated-community-leader.md#alias), where it is indeed used like you are imagining.

For the 2 patterns with Aliases in this PR I decided to keep them in there because the old titles did seem to carry some semantic, and I didn't want to judge if that was fully expressed already outside of the title. 

Another tangental thought on the Title/Alias: 
Once we publish the book, the title will be part of the URL for the pattern too. Then we should try to keep the title and URL as stable as possible so that patterns can be referenced from elsewhere without risking a broken link (for that purpose other ISC resources like the Learning Path might want to point to the patterns in the book, rather than to the patterns in the repo).

**Comment by spier** [comment]
@MaineC we are about to release the first version of our Patterns as a gitbook. Would be nice if we could get some of the Patterns titles, as that makes for an easier to consume table of contents in the book. 

Please review the diffs in this PR and let us know if you are ok with the shortened titles.

**Comment by spier** [comment]
I am moving ahead with this change as is, to get book into a prettier shape (I think so at least :)).

The original titles of these patterns have still been conserved in the `## Alias` section, so they are not lost in case the original authors of these patterns want to use them for something.

In later validation rounds, e.g. when leveling-up the pattern from Structured to Validated, we might get rid of the Aliases then if they don't provide any additional value/content as @gruetter was explaining above.

**Pull request merged**
