### PR TITLE
Enable Renovate

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://github.com/marketplace/renovate

### CODE REVIEW

**Comment by spier** [comment]
Hi @gliptak. 

As your PR does not contain any additional information, it is hard for me to understand the intention here.

Could you help me understand how we would benefit from using **renovate** for our project?

As context, we are already using the built-in dependency updates provides by GitHub (through dependabot).

Thanks

**Comment by gliptak** [comment]
thank you @spier I didn't see dependabot configuration

**Comment by spier** [comment]
Thanks @gliptak.

Just curious, how did you come across our repo?

**Comment by gliptak** [comment]
I work on improving inner-source processes and InnerSource Commons is a great resource

**Comment by spier** [comment]
Very cool @gliptak. 

If you would like to chat more InnerSource, you can also join the [ISC Slack](https://innersourcecommons.org/slack).
Maybe see you there :)

**Pull request closed without merging**
