### PR TITLE
Draft pattern: Who is using my code?

### PR DESCRIPTION
**Pull request by StingRayZA**
Initial commit of pattern Brainstormed at ISC S8 (Sprint 2019; Galway)
@gruetter

### CODE REVIEW

**Comment by lenucksi** [comment]
That looks like a nice and detailed enough pattern for a Draft. I can also confirm the described pattern.

**Comment by spier** [comment]
I would agree that the problem described in this pattern affects all InnerSource (and open source!) projects.

Content Feedback:

* Would the pattern benefit from a shorter name than "Who is using my code?"?
* Could we make the description more specific to InnerSource? i.e. how do the problems described impact a project that is used only inside of a company? (anything that is different here than for an Open Source project?)

Template Feedback:

* Misses **Patlet** section
* Should be **Status** (rather that **State**) - I know, super picky. :)
* Which labels should this issue get? I assume Pattern Maturity: **Unproven**. Not sure about the Review Step it should be in.

**Comment by lenucksi** [comment]
Hey @StingRayZA! 
We're currently trying to merge all the open pull request using our new, simplified process described in our  [contributor handbook](https://github.com/InnerSourceCommons/InnerSourcePatterns/blob/master/meta/contributor-handbook.md).

Do you think you'd have a bit of time and and are interested in addressing the things @spier pointed out above?

**Comment by StingRayZA** [comment]
I'll have a look asap 😄

**Comment by StingRayZA** [comment]
* rebased (the whole repo has been updated somewhat in the last 16 months 😉 )
* updated name (Code consumers?)
* Added (stub) Patlet section
* Updated _State_ to _Status_

As far as labels/maturity - I suppose it is unproven. This is something that still eludes us as an org - I'd love to solve it.

**Comment by spier** [comment]
Given that the pattern contains suggested solutions that are hypothetical for now, putting this pattern in "Level 1: Initial" as you already did seems sensible.

When this get's merged, let's add it to the main `README.md` as well.

**Review by lenucksi — APPROVED** [review]
Great, thanks for the quick updates! Merging this.

**Pull request merged**
