### PR TITLE
[docs] Creating new patterns in the right folder

### PR DESCRIPTION
**Pull request by spier**
It is most likely that new patterns will first go into the folder `patterns/1-initial/` and then mature from there into higher levels. 
Adding this info to the documentation.

### CODE REVIEW

**Review by gruetter — APPROVED** [review]
LGTM

**Comment by spier** [comment]
Thanks @gruetter. Feel free to merge if you are happy with the updated docs.

**Comment by gruetter** [comment]
Thanks for this, @spier !

**Comment by gruetter** [comment]
Sorry for that - mostly working with Bitbucket these days ;).

**Comment by spier** [comment]
No worries. Thanks for handling this!

**Pull request merged**
